[package]
name = "vega-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
vega-prover = { git = "https://github.com/microsoft/vega-prover", default-features = false, rev = "c0ee259053cd12eaf43ed71b5cde375452b3ee4d" }
bellpepper = "0.4"
bellpepper-core = "0.4"
ff = { version = "0.13", features = ["derive"] }
sha2 = { workspace = true }
bincode = { workspace = true }
utils = { workspace = true }
clap = { workspace = true }


[dev-dependencies]
criterion = { workspace = true }

[[bin]]
name = "sha256_mem_vega"
path = "src/bin/sha256_mem_vega.rs"

[[bench]]
name = "sha256"
harness = false
